// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATydEEjjhctBfNl-gpa2ZpCuayj7Ycp2w',
    appId: '1:162009706463:web:0a2580d0d630b841181e6a',
    messagingSenderId: '162009706463',
    projectId: 'fir-d371d',
    authDomain: 'fir-d371d.firebaseapp.com',
    storageBucket: 'fir-d371d.appspot.com',
    measurementId: 'G-G6BR2K5LDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_BXqf1GxKt9PeCOHO0FrkEpH7o9BqjtE',
    appId: '1:162009706463:android:4254363e90609f19181e6a',
    messagingSenderId: '162009706463',
    projectId: 'fir-d371d',
    storageBucket: 'fir-d371d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZqUHoyh6aau6hrFl28MwdBiDQyZ60FQ',
    appId: '1:162009706463:ios:026987882e1c6850181e6a',
    messagingSenderId: '162009706463',
    projectId: 'fir-d371d',
    storageBucket: 'fir-d371d.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZqUHoyh6aau6hrFl28MwdBiDQyZ60FQ',
    appId: '1:162009706463:ios:532d01bc55f8d1bc181e6a',
    messagingSenderId: '162009706463',
    projectId: 'fir-d371d',
    storageBucket: 'fir-d371d.appspot.com',
    iosBundleId: 'com.example.fire.RunnerTests',
  );
}
